### ISSUE TITLE
Depositor is allowed to remove parent collection in a shared collection

### ISSUE THREAD

**Issue by Karthikeya212** [samvera-labs/nurax-pre2023#255]
### Descriptive summary
Browser: Chrome  65.0.3325.181
OS: Windows 10
Use Case Number: CSN_1.12
Issue: Depositor is allowed to remove parent collection in a shared collection.

### Expected behavior
Depositor shouldn't be seeing the Remove button next to the parent collection and sub collection fields in a shared collection.

### Steps to reproduce the behavior

1. Login as a non-admin User_1
2. Create a collection (Shared collection) and add another non-admin User_2 as Depositor
3. Login as User_2 and create a new collection (Parent collection) with same type as above collection
4. Open the shared collection and add it to the Parent collection
5. Now on opening the shared collection, depositor can see Remove button next to parent collection, which shouldn't be the case. You can also add some sub collections and check that there is no Remove button next to them.
![image](https://user-images.githubusercontent.com/25850972/38427256-c06de466-3986-11e8-8bd6-7a8429626ad0.png)

**Comment by vantuyls** [comment]
@Karthikeya212 can you confirm whether you mean "delete" or "remove" in this issue title?

Is this expected behavior (as different from desired behavior)? @elrayle

**Comment by Karthikeya212** [comment]
@vantuyls Sorry, I meant "remove"

**Comment by elrayle** [comment]
Ultimately, this comes down to a UX question.  The user does have the ability (permissions) to remove subcollections from a collection they own (e.g. Parent Collection).  But so far, we have said they have to do that from the Parent Collection.  Otherwise, it gives the impression that the user is editing the subcollection where they are just a viewer or depositor.

So to be consistent, the Remove button should NOT display on the show page of a collection where the user is a viewer or depositor.  It should be available for subcollections from the page where they are an editor.

**Comment by chrisdaaz** [comment]
this appears to have been fixed. i'm not able to reproduce.

**Comment by julesies** [comment]
@elrayle I'm testing this as a viewer looking at the subcollection for an existing collection and I'm still seeing the "remove" button. 
![screen shot 2018-05-09 at 12 44 33 pm](https://user-images.githubusercontent.com/4356335/39827748-e02af9e6-5386-11e8-89c4-3d2f01e246a5.png)

**Comment by elrayle** [comment]
@julesies 

When the user is a manager of the collection being viewed, there will always be a Remove button for every parent.
* if the user is also a manager of the parent collection, then the Remove button will present a dialog confirming the remove.
* if the user is a depositor or viewer of the parent collection, then the Remove button will present a dialog telling then they do not have sufficient permissions to remove the parent collection.

**Comment by julesies** [comment]
@elrayle can you test this to confirm? what i'm seeing is that as a viewer of child collection and editor of parent collection...when viewing the child collection, i can remove the parent collection.

**Comment by julesies** [comment]
I was testing in the wrong collection. Sorry!!!!
